### ISSUE TITLE
new api?

### ISSUE THREAD

**Issue by ccharmai** [bastshoes/yandex_weather#1]
Добрый день!
В настоящее время на hass.io **(0.103.6)** данный код не работает
Я так понимаю, у яндекса сменился API. И в связи с этим:
1) Появилось разделение по ключам - теперь тестовый и постоянный ключ требуют разных запросов (forecast/informers) (_weather.py 245 строка, надо поменять informers на forecast для тестового ключа_)
2) После получения ответа через тестовый ключ возникает следующая проблема: у json'a отсутствует ключ 'forecast'. Если я правильно понимаю, то его заменили ключом 'forecasts'. (_255 строка, дописываем 's'_)
3) И после этого возникает ошибка <code>'dict' object has no attribute 'index'</code>, решить которую я пока не могу

**Comment by bastshoes** [comment]
Вроде ничего не менялось. Я на 0.104.0 и все работает. Разделение api было всегда. https://tech.yandex.com/weather/doc/dg/concepts/pricing-docpage/

Полноценный ключ стоит дорого. Тестовый работает 30 дней.
