### ISSUE TITLE
Yandex Weather on HA 2022.3

### ISSUE THREAD

**Issue by alexreddy78** [bastshoes/yandex_weather#12]
Dear Developer,

Got flw error/warning in the log:

Logger: homeassistant.helpers.frame
Source: helpers/frame.py:103 
First occurred: 17:39:08 (1 occurrences) 
Last logged: 17:39:08

Detected integration that called async_timeout.timeout with loop keyword argument. The loop keyword argument is deprecated and calls will fail after Home Assistant 2022.3. Please report issue to the custom component author for yandex_weather using this method at custom_components/yandex_weather/weather.py, line 251: async with async_timeout.timeout(5, loop=self._loop):

And custom integration is not working anymore on HA 2022.3

Kindly check and if possible fix the issue

REGARDS

ALEX

**Comment by bastshoes** [comment]
Hi!
It's been fixed long time ago. 

Pull latest weather.py from repo.

**Comment by alexreddy78** [comment]
Thanks!
