### ISSUE TITLE
Yandex.Weather, 403, Forbidden

### ISSUE THREAD

**Issue by krotish** [bastshoes/yandex_weather#2]
I've installed component and using test (30-days trial) API key

I had following errors in log: 
```
Log Details (ERROR)
Tue Feb 18 2020 14:09:24 GMT+0300 (Moscow Standard Time)
Error fetching data from Yandex.Weather, 403, Forbidden
```

and the second one: 
```
Tue Feb 18 2020 14:15:36 GMT+0300 (Moscow Standard Time)
Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 424, in _async_add_entity
    await entity.async_update_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 284, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 320, in _async_write_ha_state
    state = self.state
  File "/usr/src/homeassistant/homeassistant/components/weather/__init__.py", line 187, in state
    return self.condition
  File "/config/custom_components/yandex_weather/weather.py", line 168, in condition
    if self._weather_data.current['condition'] in v), None)
  File "/config/custom_components/yandex_weather/weather.py", line 168, in <genexpr>
    if self._weather_data.current['condition'] in v), None)
KeyError: 'condition'
```

Could you please help me to resolve an issues? 
I'm using hass.io Home Assistant 0.105.3

many thanks,
Ilya

**Comment by bastshoes** [comment]
Илья, добрый день.

Такое бывает, когда превышается порог допустимого количества запросов (50 запросов в день).

**Comment by krotish** [comment]
добрый. порог запросов совершенно точно не превышен. кроме того, сейчас по умолчанию стоит тестовый план, где они должны быть неограниченные.

**Comment by bastshoes** [comment]
Я на 0.105.5 компонент работает. После создания ключа данные начинают приходить где-то через сутки.

**Comment by AlexeyHimki** [comment]
Для тестового тарифа URL выглядит так:
https://api.weather.yandex.ru/v1/forecast?
Для тарифа Погода на вашем сайте так:
https://api.weather.yandex.ru/v1/informers?

У вас в коде используется URL для тарифа "Погода на вашем сайте"
Я выбрал этот тариф, но в логах все равно ошибка 403.
Проверяю через CURL свой ключ, все ОК:
curl -i -H "Accept: application/json" -H "Content-Type: application/json" -H "X-Yandex-API-Key: 741c32d1...36639" https://api.weather.yandex.ru/v1/informers?lat=55.75396&lon=37.620393
Ответ:
HTTP/1.1 200 OK
Content-Length: 1111
Content-Type: application/json; charset=utf-8
Date: Sat, 28 Mar 2020 12:21:15 GMT
ETag: W/"457-lfkj7waoRqOKzYf4/IPLfLf4lZA"

Но ваш компонент упорно выдает ошибку 403.

В чем может быть проблема?
