### ISSUE TITLE
Sensors

### ISSUE THREAD

**Issue by Anton-Ka** [bastshoes/yandex_weather#5]
Are any weather sensors being created?
Создаются ли какие-либо сенсоры погоды?

**Comment by bastshoes** [comment]
У интгерации weather нет сенсоров. Список доступных атрибутов сущности погода можно посмотреть здесь - https://developers.home-assistant.io/docs/core/entity/weather

**Comment by Anton-Ka** [comment]
> У интгерации weather нет сенсоров. Список доступных атрибутов сущности погода можно посмотреть здесь - https://developers.home-assistant.io/docs/core/entity/weather

Подскажите, пожалуйста, каким тогда методом я могу получить данные о погоде от сущности этой интеграции для создания пользовательского сенсора?

**Comment by bastshoes** [comment]
Есть карточка погоды.
